language: node_js
node_js: '0.10'
script:
  - grunt karma:$SAUCE_BROWSER
before_script:
  - npm install -g grunt-cli
  - grunt
branches:
  only:
    - master
    - develop
    - /^sauce-.+$/
    - /^v\d+\.\d+\.\d+$/
env:
  - SAUCE_BROWSER=remote-mac-chrome
  - SAUCE_BROWSER=remote-mac-firefox
  - SAUCE_BROWSER=remote-mac-safari
  - SAUCE_BROWSER=remote-windows-chrome
  - SAUCE_BROWSER=remote-windows-firefox
  - SAUCE_BROWSER=remote-windows-ie-11
  - SAUCE_BROWSER=remote-windows-ie-10
  - SAUCE_BROWSER=remote-windows-ie-9
  - SAUCE_BROWSER=remote-linux-chrome
  - SAUCE_BROWSER=remote-linux-firefox
  - SAUCE_BROWSER=remote-ipad
  - SAUCE_BROWSER=remote-iphone
  - SAUCE_BROWSER=remote-android
