language: node_js
node_js: '5'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - gulp remote:$TEST
sudo: false
cache:
  directories:
    - node_modules
env:
  matrix:
    - CXX=g++-4.8 TEST=unit-mac-chrome
    - CXX=g++-4.8 TEST=unit-mac-firefox
    - CXX=g++-4.8 TEST=unit-mac-safari
    - CXX=g++-4.8 TEST=unit-windows-chrome
    - CXX=g++-4.8 TEST=unit-windows-firefox
    - CXX=g++-4.8 TEST=unit-windows-ms-edge
    - CXX=g++-4.8 TEST=unit-windows-ie-11
    - CXX=g++-4.8 TEST=unit-linux-chrome
    - CXX=g++-4.8 TEST=unit-linux-firefox
    - CXX=g++-4.8 TEST=unit-ipad
    - CXX=g++-4.8 TEST=unit-iphone
    - CXX=g++-4.8 TEST=unit-android
