language: node_js
node_js: '0.10'
script:
  - grunt test:$BROWSER
before_install:
  - npm install -g grunt-cli
  - source config/sauce.sh
before_script:
  - grunt lodash
env:
  matrix:
    - BROWSER=mac-chrome
    - BROWSER=mac-firefox
    - BROWSER=mac-safari
    - BROWSER=windows-chrome
    - BROWSER=windows-firefox
    - BROWSER=windows-ie-11
    - BROWSER=windows-ie-10
    - BROWSER=windows-ie-9
    - BROWSER=linux-chrome
    - BROWSER=linux-firefox
    - BROWSER=ipad
    - BROWSER=iphone
    - BROWSER=android
addons:
  sauce_connect:
    username: "quill-master"
    access_key:
      secure: "Mgrp2KtzPaZIG36ZoKleP2WneOamT5WFIFUDhS0mj4jbAFSjXWGnRJI7R0XuT9wDmS/f0gIsxazFELXher9CAmsa3VINFW3cVztykqIMSD5HBhyOyTuVzi6q3tvhx2u/OCxqV8o12XrgGJnKwnBuHbapHqhM39CJI2UjYhsgct8="
