name: Quill - A Rich Text Editor with an API
timezone: America/Los_Angeles
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
version: 0.20.1
cdn: //cdn.quilljs.com/
github: https://github.com/quilljs/quilljs.github.io/tree/1.0
