name: Quill - A Rich Text Editor with an API
timezone: America/Los_Angeles
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
version: 1.0.2
cdn: //cdn.quilljs.com/
github: https://github.com/quilljs/quilljs.github.io/tree/master
quill: quill.min.js
highlightjs: //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0
katex: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0
