name: Quill - A Rich Text Editor with an API
timezone: America/Los_Angeles
relative_permalinks: false
highlighter: pygments
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
version: 0.20.1
cdn: cdn.quilljs.com
