name: Quill - Open Source Rich Text Editor
timezone: America/Los_Angeles
relative_permalinks: false
highlighter: pygments
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
version: 0.16.0
